- hosts: vcenter
  remote_user: "{{ vcenter_user }}"
  gather_facts: false
  connection: local
  pre_tasks:
  - name: install package
    hosts: localhost
    remote_user: "{{ localhost_user }}"
    apt:
      update_cache: yes
      name: "{{ item }}"
      state: present
    loop: [ 'nmap']
    become: yes

  roles:
    - checkip

