- hosts: master

  remote_user: "{{ ansible_ssh_user }}"
  become_method: sudo
  gather_facts: yes
  vars_files:
  - vars/woker.yml
  pre_tasks:
  - name: Pre install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    become: yes


