- name: install package
  hosts: localhost
  remote_user: "{{ localhost_user }}"
  pre_tasks:
  - name: Pre install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    become: yes

  tasks:
  - name: dmm
    apt:
      update_cache: yes
      name: "{{ item }}"
      state: present
    loop: [ 'nmap']
    become: yes

  roles:
    - check_ip

